<?xml version="1.0"?>


<robot xmlns:xacro="http://ros.org/wiki/xacro" name="microver">

    <!-- Controller for the 4 wheeled differential drive microver inchallah-->
    <gazebo>

        <plugin name="skid_steer_drive" filename="libgazebo_ros_diff_drive.so">

            <num_wheel_pairs>2</num_wheel_pairs>
            <left_joint>front_left_wheel_joint</left_joint>
            <right_joint>front_right_wheel_joint</right_joint>
            <left_joint>back_left_wheel_joint</left_joint>
            <right_joint>back_right_wheel_joint</right_joint>

            <wheel_separation>${WIDTH + (2*LEG_WIDTH) + WHEEL_WIDTH}</wheel_separation>
            <!-- <wheel_separation>${WIDTH + (2*LEG_WIDTH) + WHEEL_WIDTH}</wheel_separation> -->

            <wheel_diameter>${2*WHEEL_RADIUS}</wheel_diameter>
            <!-- <wheel_diameter>${2*WHEEL_RADIUS}</wheel_diameter> -->

            <max_wheel_torque>5</max_wheel_torque>
            <max_wheel_acceleration>5.0</max_wheel_acceleration>
            
            <!-- output -->
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>

            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_link</robot_base_frame>

        </plugin>

    </gazebo>

</robot>